### PR TITLE
feat(PieChart): add pieExtendAngle parameter

### PR DESCRIPTION
**Pull request by mediavrog**
Support drawing half pie charts, or any angle pie charts like a 90 degree fan.

Based on the work in https://github.com/KoalaPlot/koalaplot-core/pull/80

### CODE REVIEW

**Comment by mediavrog** [comment]
Kinda not feeling the min angle of 1, as it seems arbitrary.
What do you think? Does your library have any similar api?

I guess we could just set the range to 0 exclusive to 360.
Or allow 0..360 and map 0 to a full circle.

**Comment by gsteckman** [comment]
A value 0 < x <= 360 is OK. Practically speaking I don't expect people to use very small values, because it won't be a practical way to display information. But this range will prevent a divide by 0 and ensure correct usage.

**Comment by mediavrog** [comment]
done

**Review by gsteckman — APPROVED** [review]

**Comment by gsteckman** [comment]
Thanks for your contributions.

**Comment by mediavrog** [comment]
Thanks for this library!
Using it for a cross-platform mobile app and will contribute more whenever necessary

**Pull request merged**
