### PR TITLE
Add ColoredStairstepPlot: StairstepPlot with different color for each category (Y-value)

### PR DESCRIPTION
**Pull request by KentVu**
Example usage:

```kotlin
      val colors = generateHueColorPalette(4)
      ColoredStairstepPlot(
        sleepCycles.map { Point(it.startCycle, it.depth) }, // Deserialized JSON.
        LineStyle(
          brush = SolidColor(colors[0]),
          strokeWidth = 2.dp
        ),
        {
        // Arbitrarily select color for each category (Y-value)
        when(it) {
          SleepDepth.awake ->
            LineStyle(
              brush = SolidColor(colors[0]),
              strokeWidth = 4.dp
            )

          SleepDepth.REM ->
            LineStyle(
              brush = SolidColor(colors[1]),
              strokeWidth = 4.dp
            )

          SleepDepth.light ->
            LineStyle(
              brush = SolidColor(colors[2]),
              strokeWidth = 4.dp
            )

          SleepDepth.deep ->
            LineStyle(
              brush = SolidColor(colors[3]),
              strokeWidth = 4.dp
            )
        }
        },
```

Generated plot image:

image

### CODE REVIEW

**Comment by gsteckman** [comment]
Thanks for contributing. I think if lineStyle.strokeWidth is wider than levelLineStyle.strokeWidth, you will see it in the "background" of the level part of the line. In your example, the level lines were 4.dp so they completely covered the 2.dp lineStyle. One solution for that is to not draw the path from ```drawConnectorLine``` at line 328, and instead draw the vertical part of the line together with the horizontal parts in ```drawLevelLines```.

**Comment by KentVu** [comment]
Thank you for the review. That's what on my TODO list already ;).
 
BTW, There's couple of issues that'll need your help:
- Is the function name correct, I'm not a native speaker so there may be a more proper name for this.
- Or should this be merged into `StairstepPlot`, adding `drawLevelLines` parameter?
  This would involve changing `GeneralLinePlot`'s signature to accept `drawConnectorLine` as `DrawScope`'s receiver. (instead of `Path`'s receiver)

**Comment by gsteckman** [comment]
The function name could also be ```StairstepPlot``` and then function overloading would select the right one depending on if the caller provided the ```levelLineStyle``` parameter or not. 

Because ```ColoredStairStepPlot``` requires starting a new line segment for each segment of the plot, I think the ```GeneralLinePlot``` implementation should be kept separate. This is primarily because, if someone is using a line stroke that is dashed, when each line segment is started the phase will restart at 0. ```StairstepPlot``` plots the entire line created by ```GeneralLinePlot``` as a single path so the dash phase will be continuous over the whole path. That does mean some of the ```GeneralLinePlot``` code will be duplicated but it's not much and trying to factor out the common parts may not be worth the trade-off in increased complexity. But if you have ideas on how to do it elegantly please make a suggestion.

In ```ColoredStairStepPlot```, a continuous path of the line should still be generated (```mainLinePath```) for use as part of the area boundary for when the ```areaStyle``` is not null.

**Comment by KentVu** [comment]
@gsteckman 
I utilized a visitor pattern to avoid duplicating code, (between `drawConnectorLine` and drawing each line segment),
besides, I've added a flag that allow `overlayDrawing`, since if `levelLineStyle` is bigger than `lineStyle`, enabling it would give a nice _antialiasing_ effect (like in PR description), otherwise, aliasing at each vertex can be easily spotted.

image

The following is with `overlayDrawing` enabled but `lineStyle` is bigger (you can notice the red background over magenta ones)

image

**Comment by gsteckman** [comment]
@KentVu Have you tried using ```StrokeCap.Square``` when drawing the level lines? I think that might eliminate the artifact. One problem with using overlayDrawing=true is that if you use a dash pattern for the level line, and it doesn't match with the dash and phase of the lineStyle, then you will see it "underneath" the level line. So ideally we can figure out a way to draw the level lines and the vertical lines without an "artifact".

The detek check is failing. Please run the detekt gradle task on the code and correct any failures it finds (it will flag deprecations, you don't need to correct those they are only warnings).

Thanks!

**Comment by KentVu** [comment]
@gsteckman 

As per your suggestion, I've removed the overlayDrawing parameter and tried out the StrokeCap, the 'artifact' has eliminated nicely.
I've also made StrokeCap an optional parameter to leave users control what they prefer.
Beside, there's another issue that the vertical lines overlap the level lines, which I've addressed.

Here is for StrokeCap.Square, but the vertical lines overlapping level lines:
image

Here is for StrokeCap.Round (which I personally prefer), with overlapping issue fixed:
image

**Comment by gsteckman** [comment]
Have you tested this with a filled area? I think the logic for creating ```mainLinePath``` has changed, and now the area's bounding path will not match the line drawn at the code below the ```//drawLevelLines``` comment. For example in the first iteration of ```mainLinePath``` the ```moveTo``` and ```lineTo``` will both be to the scaled ```points[0]``` and so no line is drawn.

To avoid the partial overlapping you observed, two passes can be made: The first pass to draw the vertical lines, and the second pass to draw the horizontal lines. Then there shouldn't be the need for the correction factors to compensate for the stroke width, since the horizontal lines will then always draw on top of the vertical lines.

**Comment by KentVu** [comment]
I've tested with a filled area, seems like it was properly drawn:

スクリーンショット 2024-01-26 13 12 53

I'll try to implements the two passes drawing as per your suggestion.

**Comment by KentVu** [comment]
@gsteckman 
I've implemented 2 pass drawing as per your suggestion, everything seems working fine as my observation.
Please kindly review ;)

**Review by gsteckman — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
