### PR TITLE
feat(PieChart): add pieStartAngle parameter to configure the starting angle of the pie chart

### PR DESCRIPTION
**Pull request by mediavrog**
As the title says, I wanted to be able to configure the starting angle of my pie chart (https://github.com/KoalaPlot/koalaplot-core/issues/79)

Only issue I found is when the angle is set to some small fraction like 179.999, then somewhere the logic will produce too many label placeables and it will crash. Haven't found the origin for that yet

FYI: I also tried to add a configurable `pieMaxAngle` to be able to create half pies, but when creating `makePieSliceData` with this 180 degree angle instead of full circle, the code crashed somewhere else.

### CODE REVIEW

**Comment by mediavrog** [comment]
For some reason, getting crashes with some data, not with others when setting the startAngle to -180 :(

```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:434)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.computeSize-bSu-EZI$koalaplot_core_release(PieMeasurePolicy.kt:204)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.checkDiameter-3p2s80s(PieMeasurePolicy.kt:184)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.findMaxDiameter_NN6Ew_U$lambda$11(PieMeasurePolicy.kt:168)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.$r8$lambda$45Fxsl3YK_27lX1d1JiGKIp1eh4(Unknown Source:0)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy$$ExternalSyntheticLambda0.invoke(Unknown Source:14)
                                                                                                    	at io.github.koalaplot.core.util.UtilKt.maximizeUnguarded(Util.kt:93)
                                                                                                    	at io.github.koalaplot.core.util.UtilKt.maximize(Util.kt:66)
                                                                                                    	at io.github.koalaplot.core.util.UtilKt.maximize$default(Util.kt:55)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.findMaxDiameter-NN6Ew-U(PieMeasurePolicy.kt:164)
                                                                                                    	at io.github.koalaplot.core.pie.PieMeasurePolicy.measure-L1NQ6kE$koalaplot_core_release(PieMeasurePolicy.kt:143)
                                                                                                    	at io.github.koalaplot.core.pie.PieChartKt$PieChart$5.invoke$lambda$4(PieChart.kt:255)
                                                                                                    	at io.github.koalaplot.core.pie.PieChartKt$PieChart$5.$r8$lambda$Xvyq5xcjezsxcwsUrB1eNJvP-D4(Unknown Source:0)
                                                                                                    	at io.github.koalaplot.core.pie.PieChartKt$PieChart$5$$ExternalSyntheticLambda0.invoke(Unknown Source:36)
```

**Comment by gsteckman** [comment]
I think one issue is that the `matchingQuadrant` isn't being found. Changing from `first()` to `find()` is only covering that up, not resolving the root issue. The quadrant is defined with a specific angle range, starting at -90 and proceeding in the positive direction from there. So if a pie slice center angle has a value < -90, then it's going to cause a problem because the quadrant for the label won't be found. To resolve this, the logic of finding the quadrant is going to have to be made general purpose and account for the fact that angles "wrap" and more than one value can represent the same angle (e.g. 0, 360, 720 all represent the same angle). Taking the sine and cosine of the angle and assigning to a quadrant based on the sign of the results should work, plus accounting for the rotation angle being "backward" from common math conventions because the screen coordinates use an inverted y-axis.

**Comment by mediavrog** [comment]
Without having had a deeper look, do you think it might be enough for the features of the current pie chart implementation to create a

`Quadrant.from(angleRange: ClosedFloatingPointRange<Float>)`

method to replace the current find logic, which returns the quadrant that the range covers the most?

**Comment by mediavrog** [comment]
@gsteckman Please have a look again. I think this could be enough to adress the issue.

**Comment by mediavrog** [comment]
> That was a good idea to make a `from()` function. That should solve that issue. Did it help with the issue when the value had many digits like 179.999?

I will check again

**Comment by mediavrog** [comment]
> Would you mind making a unit test for the new function?

I added some unit tests; turns out the inclusive ranges of quadrants throws our intuition a small curveball, as a value of -90 will get normalized to 270, thus returning Quadrant.NorthWest.

I think this is acceptable, as at this angle either quadrant is technically fine and as long as the normalization is stable it should not lead to issues. The other option would be to create OpenEndRanges for quadrants (inclusive..exclusive using `..<`). Let me know what you think

**Comment by mediavrog** [comment]
done

**Review by gsteckman — APPROVED** [review]

**Comment by gsteckman** [comment]
Thanks for contributing!

**Pull request merged**
