### PR TITLE
feat(PieChart)!: add content padding for holeContent for finer layout control

### PR DESCRIPTION
**Pull request by mediavrog**
This is a BREAKING change, as it alters the default size of the holeContent box.

To be able to draw up to the pie chart hole edges (for example a single line of small text), measure the holeContent layout box to the size of the hole diameter, and pass contentPadding so the consumer may apply that to draw safely inside the pie hole without intersecting the pie chart.

Contains small adjustments (BoxScope declaration) from https://github.com/KoalaPlot/koalaplot-core/pull/83, but is otherwise independent of that PR

### CODE REVIEW

**Comment by gsteckman** [comment]
Interesting idea. Should we add a clip to the Box so the user cannot write into the pie area?

**Comment by mediavrog** [comment]
Yeah, that sounds reasonable. I cannot imagine a use case where it would be wanted to draw into the pie chart, but maybe I am lacking imagination here :)

**Comment by gsteckman** [comment]
Hi, if you go ahead and add the clip, then I can merge the PR.

**Comment by mediavrog** [comment]
@gsteckman added the clip

**Review by gsteckman — APPROVED** [review]

**Pull request merged**
